POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "admin1@gmail.com",
  "password": "null" 
}

### signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "1" 
}

### find who am i
GET  http://localhost:3000/auth/whoami

### Signout
POST  http://localhost:3000/auth/signout 

### find user
GET  http://localhost:3000/auth/4

### Find all users with given email
GET http://localhost:3000/auth?email=user2@gmail.com

### Delete user with requested id
DELETE http://localhost:3000/auth/2


### update a user
PATCH http://localhost:3000/auth/10
Content-Type: application/json

{
  "password": "update@gmail.com"
}